import { NextResponse } from "next/server";
import { pool } from "@/lib/db";

// SQL‑запросы для создания таблиц
const createTablesQuery = `
  CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL
  );

  CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    weight INTEGER DEFAULT 0,
    unit VARCHAR(10),
    description TEXT,
    composition TEXT,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    price DECIMAL(10, 2) NOT NULL,
    old_price DECIMAL(10, 2),
    remains REAL DEFAULT 0.0,
    is_active BOOLEAN DEFAULT TRUE,
    status VARCHAR(20) DEFAULT 'default',
    to_carousel BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  );
  
  CREATE TABLE IF NOT EXISTS customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email TEXT,
    password TEXT NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    is_admin BOOLEAN DEFAULT FALSE,
    bonus_created_at TIMESTAMPTZ DEFAULT NULL,
    bonus_received BOOLEAN DEFAULT FALSE,
    bonus_position_id INTEGER,
    bonus_amount INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS temp_users (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    password_hash TEXT NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL,
    verification_code VARCHAR(6) NOT NULL,
    verification_expires TIMESTAMP NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
  );
    
  CREATE TABLE IF NOT EXISTS cart_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity REAL DEFAULT 0,
    total_price DECIMAL(10, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS addresses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    country VARCHAR(50) DEFAULT 'Россия',
    city VARCHAR(100) NOT NULL,
    address VARCHAR(100),
    street VARCHAR(100),
    house VARCHAR(20),
    entrance VARCHAR(5),
    floor VARCHAR(5),
    apartment VARCHAR(5),
    intercom_number VARCHAR(20),
    postal_code VARCHAR(20),
    additional_info TEXT,
    is_default BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    address_id INTEGER REFERENCES addresses(id) ON DELETE CASCADE,
    type VARCHAR(20) NOT NULL DEFAULT 'доставка',
    cart_items INTEGER[] NOT NULL,
    total_items INTEGER NOT NULL,
    total_sum DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'создан',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity REAL DEFAULT 0,
    total_price DECIMAL(10, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS content (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL DEFAULT 'news',
    title VARCHAR(500),
    info TEXT,
    media_url TEXT,
    link_href TEXT,
    link_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS consent_ppd (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    values TEXT,
    purpose TEXT,
    ip_address INET NOT NULL,          -- Обязательно
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valid_until TIMESTAMPTZ
  );

  CREATE TABLE IF NOT EXISTS consent_cookies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    consent_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cookie_categories JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    revoked_at TIMESTAMPTZ,
    ip_address INET NOT NULL,          -- Обязательно
    user_agent TEXT NOT NULL,         -- Обязательно
    page_url TEXT NOT NULL,           -- Обязательно
    consent_method VARCHAR(20) NOT NULL, -- Обязательно
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  
  CREATE TABLE IF NOT EXISTS security_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address VARCHAR(45) NOT NULL, 
    action VARCHAR(100) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    details JSONB 
  );

  CREATE TABLE IF NOT EXISTS temp_login_codes (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL,
    code VARCHAR(6) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES customers(id)
  );
`;

// SQL‑запросы для создания индексов
const createIndexesQuery = `
  -- Индексы для таблицы products
  CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
  CREATE INDEX IF NOT EXISTS idx_products_is_active ON products(is_active);
  CREATE INDEX IF NOT EXISTS idx_products_remains ON products(remains);
  CREATE INDEX IF NOT EXISTS idx_products_name ON products(name);
  CREATE INDEX IF NOT EXISTS idx_products_to_carousel ON products(to_carousel);
  CREATE INDEX IF NOT EXISTS idx_products_price ON products(price);
  CREATE INDEX IF NOT EXISTS idx_products_created_at ON products(created_at);

  -- Индексы для таблицы customers
  CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);
  CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);
  CREATE INDEX IF NOT EXISTS idx_customers_is_admin ON customers(is_admin);
  CREATE INDEX IF NOT EXISTS idx_customers_created_at ON customers(created_at);

  -- Индексы для таблицы cart_items
  CREATE INDEX IF NOT EXISTS idx_cart_items_customer_id ON cart_items(customer_id);
  CREATE INDEX IF NOT EXISTS idx_cart_items_product_id ON cart_items(product_id);
  CREATE INDEX IF NOT EXISTS idx_cart_items_created_at ON cart_items(created_at);

  -- Индексы для таблицы addresses
  CREATE INDEX IF NOT EXISTS idx_addresses_customer_id ON addresses(customer_id);
  CREATE INDEX IF NOT EXISTS idx_addresses_city ON addresses(city);
  CREATE INDEX IF NOT EXISTS idx_addresses_is_default ON addresses(is_default);

  -- Индексы для таблицы orders
  CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders(customer_id);
  CREATE INDEX IF NOT EXISTS idx_orders_address_id ON orders(address_id);
  CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
  CREATE INDEX IF NOT EXISTS idx_orders_type ON orders(type);
  CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
  CREATE INDEX IF NOT EXISTS idx_orders_updated_at ON orders(updated_at);

  -- Индексы для таблицы order_items
  CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
  CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items(product_id);

  -- Индексы для таблицы content
  CREATE INDEX IF NOT EXISTS idx_content_type ON content(type);
  CREATE INDEX IF NOT EXISTS idx_content_title ON content(title);
  CREATE INDEX IF NOT EXISTS idx_content_created_at ON content(created_at);

  -- Индексы для таблицы consent_ppd
  CREATE INDEX IF NOT EXISTS idx_consent_ppd_customer_id ON consent_ppd(customer_id);
  CREATE INDEX IF NOT EXISTS idx_consent_ppd_created_at ON consent_ppd(created_at);
  CREATE INDEX IF NOT EXISTS idx_consent_ppd_valid_until ON consent_ppd(valid_until);

  -- Индексы для таблицы consent_cookies
  CREATE INDEX IF NOT EXISTS idx_consent_cookies_customer_id ON consent_cookies(customer_id);
  CREATE INDEX IF NOT EXISTS idx_consent_cookies_status ON consent_cookies(status);
  CREATE INDEX IF NOT EXISTS idx_consent_cookies_created_at ON consent_cookies(created_at);
  CREATE INDEX IF NOT EXISTS idx_consent_cookies_revoked_at ON consent_cookies(revoked_at);

  -- Индексы для таблицы security_logs
  CREATE INDEX IF NOT EXISTS idx_security_logs_ip_address ON security_logs(ip_address);
  CREATE INDEX IF NOT EXISTS idx_security_logs_action ON security_logs(action);
  CREATE INDEX IF NOT EXISTS idx_security_logs_timestamp ON security_logs(timestamp);

  -- Индексы для быстрой проверки кода
  CREATE INDEX IF NOT EXISTS idx_temp_users_email_code ON temp_users(email, verification_code);
  CREATE INDEX IF NOT EXISTS idx_temp_login_codes_email_code ON temp_login_codes(email, code);
`;

export async function GET() {
  try {
    await pool.query("BEGIN");
    await pool.query(createTablesQuery);
    await pool.query(createIndexesQuery);
    await pool.query("COMMIT");

    return NextResponse.json(
      {
        success: true,
        message: "Таблицы и индексы созданы",
      },
      { status: 200 },
    );
  } catch (error) {
    // Откатываем транзакцию в случае ошибки
    await pool.query("ROLLBACK");
    return NextResponse.json(
      {
        success: false,
        error: "Ошибка при создании таблиц и индексов",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}
