import { NextResponse } from "next/server";
import { pool } from "@/lib/db";

// SQL‑запросы для создания таблиц
const createTablesQuery = `
  CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL
  );

  CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    weight INTEGER DEFAULT 0,
    unit VARCHAR(10),
    description TEXT,
    composition TEXT,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    price DECIMAL(10, 2) NOT NULL,
    old_price DECIMAL(10, 2),
    remains REAL DEFAULT 0.0,
    is_active BOOLEAN DEFAULT TRUE,
    status VARCHAR(20) DEFAULT 'default',
    to_carousel BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  );
  
  CREATE TABLE IF NOT EXISTS customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email TEXT,
    password TEXT NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    is_admin BOOLEAN DEFAULT FALSE,
    bonus_created_at TIMESTAMPTZ DEFAULT NULL,
    bonus_received BOOLEAN DEFAULT FALSE,
    bonus_position_id INTEGER,
    bonus_amount INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  );
    
  CREATE TABLE IF NOT EXISTS cart_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity REAL DEFAULT 0,
    total_price DECIMAL(10, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS addresses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    country VARCHAR(50) DEFAULT 'Россия',
    city VARCHAR(100) NOT NULL,
    address VARCHAR(100),
    street VARCHAR(100),
    house VARCHAR(20),
    entrance VARCHAR(5),
    floor VARCHAR(5),
    apartment VARCHAR(5),
    intercom_number VARCHAR(20),
    postal_code VARCHAR(20),
    additional_info TEXT,
    is_default BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    address_id INTEGER REFERENCES addresses(id) ON DELETE CASCADE,
    type VARCHAR(20) NOT NULL DEFAULT 'доставка',
    cart_items INTEGER[] NOT NULL,
    total_items INTEGER NOT NULL,
    total_sum DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'создан',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity REAL DEFAULT 0,
    total_price DECIMAL(10, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS consent_ppd (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    values TEXT,
    purpose TEXT,
    ip_address INET NOT NULL,          -- Обязательно
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valid_until TIMESTAMPTZ
  );

  CREATE TABLE IF NOT EXISTS consent_cookies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    consent_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cookie_categories JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    revoked_at TIMESTAMPTZ,
    ip_address INET NOT NULL,          -- Обязательно
    user_agent TEXT NOT NULL,         -- Обязательно
    page_url TEXT NOT NULL,           -- Обязательно
    consent_method VARCHAR(20) NOT NULL, -- Обязательно
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
`;

export async function GET() {
  try {
    await pool.query("BEGIN");
    await pool.query(createTablesQuery);
    await pool.query("COMMIT");

    return NextResponse.json(
      {
        success: true,
        message: "Таблицы созданы, данные внесены",
      },
      { status: 200 },
    );
  } catch (error) {
    // Откатываем транзакцию в случае ошибки
    await pool.query("ROLLBACK");
    console.error("Ошибка при создании таблиц:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Ошибка при создании таблиц и индексов",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}
