import type { Metadata } from "next";
import { font_default } from "@/lib/fonts";
import Header from "@/components/UI/header";
import { ThemeProviderWrapper } from "@/components/theme-provider-wrapper";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* <Script
          id="theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            (function() {
              const theme = localStorage.getItem('theme') || 'system';
              document.documentElement.setAttribute('data-theme', theme);
              })();
              `,
          }}
        /> */}
      </head>
      <body className={`${font_default.className} antialiased`}>
        <ThemeProviderWrapper>
          <Header />
          {children}
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
